---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  dependsOn:
  - name: monitoring-kustomization-prometheus-stack
  interval: 1m0s
  path: ./monitoring/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-source-prometheus-stack
