---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-kustomization-prometheus-stack
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./monitoring/controllers/kube-prometheus-stack
  prune: false
  sourceRef:
    kind: GitRepository
    name: monitoring-source-prometheus-stack
